name: Latest

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: '0 0 * * *' # Run daily to check for updates
  workflow_dispatch:
    inputs:
      version:
        description: 'OOYE version to build (tag, branch, or "latest")'
        required: true
        default: 'latest'

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: y0ngg4n/ooye-docker

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest OOYE tag
        id: get-tag
        run: |
          LATEST_TAG="main"
          LATEST_HASH=f7ba176a7e37e13950490422def3e5386ed3dd40
          echo "tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
          echo "hash=${LATEST_HASH}" >> $GITHUB_OUTPUT
          echo "Latest tag found: ${LATEST_TAG} (${LATEST_HASH})"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}/
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push Hash Tag
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v3.0
          build-args: |
            OOYE_VERSION=${{ steps.vars.outputs.version }}

      
